### ISSUE TITLE
suggestions for cutoff scores when using the pre-trained model

### ISSUE THREAD

**Issue by jvollme** [leylabmpi/DeepMAsED#10]
In the DeepMased-publication two cutoff scores are mentioned: "conservative" and "relaxed". I would assume, when running DeepMasEd based on the provided pre-trained Model, I could use the same cutoff-scores as a rough starting point?
However i can't seem find concrete values for these cutoff scores in the publication or supplementary material.

Could you provide some suggestions for possible cutoff scorers when using the pre-trained models?

**Comment by nick-youngblut** [comment]
Thanks @jvollme for your interest in DeepMAsED! I advise you to use [ResMiCo](https://github.com/leylabmpi/ResMiCo) instead of DeepMAsED, given that it will generalize much better to novel data, especially with our recent updates to the model (the updated manuscript is soon to be published).

**Comment by jvollme** [comment]
Thanks I will definitely try it out. However, since I already have made the calculations with deepmased, would it still be possible to provide a rough ballpark for reasanoble score cutoffs when using deepmased?

**Comment by nick-youngblut** [comment]
I definitely recommend re-doing the calculations with resmico. If you still have the BAM files, then it should be very fast & straight-forward. 

With that said, I recommend assessing the AUCPR curves in the DeepMAsED and ResMiCo papers to determine the appropriate cutoff for your particular needs (high precision vs high recall).

**Comment by jvollme** [comment]
I am sorry but i am afraid i am a bit too dumb: These curves plot precision against recall values. But where do i see which specific **_score cutoffs_** are associated with which recall and/or precision value? Just from these plots i don't seem to be able to determine any specific score cutoffs...

**Comment by helgako** [comment]
Hi @jvollme, 
That is a very good question! Indeed, exact cutoffs are not given in the DeepMAsED paper. They are **0.145** and **0.308**. Thank you for asking.

**Comment by jvollme** [comment]
thanks!
