### ISSUE TITLE
Contigs from hybrid assembly

### ISSUE THREAD

**Issue by tthye1** [leylabmpi/DeepMAsED#7]
Hello,

I want to check contigs  generated with a hybrid assembly approach (Nanopore / Illumina reads). Can you provide the appropriate DeepMAsED settings to achieve this?

Best wishes,

Thorsten

**Comment by nick-youngblut** [comment]
Sorry, but we haven't run DeepMAsED on hybrid assemblies. You could train your own model, but you'd need to provide the training data. We are working on v2.0, which hopefully will have direct support for hybrid assemblies.
